{
  "file": "core/src/result.rs",
  "name": "<result::Result<i128, num::error::TryFromIntError> as ops::try_trait::Try>::branch",
  "hash": "495925423564812569415067967488279669908",
  "hash_direct": "109036982672091681665474050042359044778",
  "src": "fn branch(self) -> ControlFlow<Self::Residual, Self::Output> {\n        match self {\n            Ok(v) => ControlFlow::Continue(v),\n            Err(e) => ControlFlow::Break(Err(e)),\n        }\n    }"
}
